### ISSUE TITLE
Polls of old app not compatible with rework

### ISSUE THREAD

**Issue by RealRancor** [v1r0x/polls#2]
Hi,

it seems the polls created with the old app are not compatible with the rework. After upgrading the following is shown:

```
{"reqId":"RWzEMgu2nwJphuSX+\/sx","remoteAddr":"xxx","app":"index","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"hash\\\" for route \\\"polls.page.edit_poll\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php(140): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'polls.page.edit...', false, Array, Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(325): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('polls.page.edit...', Array, false)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/cachingrouter.php(56): OC\\\\Route\\\\Router->generate('polls.page.edit...', Array, false)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('polls.page.edit...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/polls\\\/templates\\\/main.tmpl.php(101): OC\\\\URLGenerator->linkToRoute('polls.page.edit...', Array, true)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(160): include('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template\\\/base.php(138): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/ownclo...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(211): OC\\\\Template\\\\Base->fetchPage()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/http\\\/templateresponse.php(156): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'index')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/polls\\\/')\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":167}","level":3,"time":"2016-02-21T20:29:53+01:00"}
```

I think its probably too much work to make a converter so it could make sense to warn users that they should delete polls of the old apps before installing the new rework.

**Comment by v1r0x** [comment]
Good point, will add a warning to the apps page.
