### ISSUE TITLE
Creating a poll leads to Internal Server Error

### ISSUE THREAD

**Issue by quizilkend** [v1r0x/polls#88]
Hey,

I upgraded to NC10.0.1 and the polls app was gone. So I installed it again and now when I create a poll I get an internal server error.

```
Interner Serverfehler
Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
Bitte wende dich an den Serveradministrator, falls dieser Fehler mehrfach auftritt, und füge deiner Anfrage die untenstehenden technischen Details bei.
Weitere Details können im Serverprotokoll gefunden werden.
Technische Details
Entfernte Adresse: 217.247.207.227
Anforderungskennung: WAiAzX8AAQEAACxfKJcAAAAE
```
I do find nothing in the logs.

Do you have any idea, what is wrong?

**Comment by v1r0x** [comment]
Which version did you have before the upgrade and which now?
Maybe this is related to a column in the database I added in one of the PR branches or in current master, which is now missing in your new version.

**Comment by quizilkend** [comment]
I now have 0.7.1 and I don't know which version I had before.

I don't need the polls I created before. Could deleting the "app data" solve the problem?

**Comment by v1r0x** [comment]
you could drop all tables staring with `oc_poll_`. Don't know if there is a polls entry in one of the nc-core tables.
First, you could try to increase the app version in the `appinfo/info.xml` file and set it to something like `0.7.1.1` and force a DB upgrade.

**Comment by quizilkend** [comment]
Okay, you mean I would change the app version and then run occ upgrade?

**Comment by v1r0x** [comment]
Exactly

**Comment by quizilkend** [comment]
Then I get:
Nextcloud is already latest version

**Comment by v1r0x** [comment]
Strange...I'll try to upload a new version this weekend. You could then try this version, maybe it will work again.
But do you still have no errors in your nextcloud log? (If you switched from oc to nc, don't forget to look at `data/nextcloud.log` instead of `data/owncloud.log`. Happened to me :wink: )

**Comment by quizilkend** [comment]
Hey,
actually I had a problem with logging, thanks for the hint.
Now I do get an error in the logs.

It's quite long and I don't know exactly what it means. But there seems to be a missing column...

`{"reqId":"WAoszn8AAQEAAFA-dMoAAAAJ","remoteAddr":"46.5.46.67","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_polls_events`(`title`,`description`,`owner`,`created`,`hash`,`is_anonymous`,`access`,`type`) VALUES(?,?,?,?,?,?,?,?)' with params [\\\"Treffen\\\", \\\"\\\", \\\"samuel\\\", \\\"2016-10-21 14:57:18\\\", \\\"nuxKqChrBWL41XVV\\\", \\\"0\\\", \\\"registered\\\", 0]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_anonymous' in 'field list'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(174): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(76): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(252): OC_DB_StatementWrapper->execute()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(126): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/polls\\\/controller\\\/pagecontroller.php(334): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OCA\\\\Polls\\\\Db\\\\Event))\\n#6 [internal function]: OCA\\\\Polls\\\\Controller\\\\PageController->insertPoll('event', 'Treffen', '', 'samuel', Array, '', 'registered', '', NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'insertPoll')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(111): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'insertPoll')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('PageController', 'insertPoll', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(983): OC\\\\Route\\\\Router->match('\\\/apps\\\/polls\\\/ins...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","level":3,"time":"October 21, 2016 16:57:18","method":"POST","url":"\/apps\/polls\/insert","user":"samuel"}`

**Comment by v1r0x** [comment]
I had the same problem. A db upgrade worked for me. You could try to set the version to something higher, e.g. `0.7.1.9`.
